### ISSUE TITLE
你好 现在官网好像下载不了数据集了 可以求一份数据吗

### ISSUE THREAD

**Issue by woxiangzhuandaqian** [yranky/UserOverdueBehaviorPrediction#1]

**Comment by yranky** [comment]
可以下载的

**Comment by woxiangzhuandaqian** [comment]
谢谢大佬 已下载

**Comment by yranky** [comment]
![image](https://user-images.githubusercontent.com/53134806/204083230-693e4d2b-e0f8-4742-a19b-4349e83c41b3.png)
训练集：https://s3.cn-north-1.amazonaws.com.cn/files.datafountain.cn/uploads/images/competitions/449/train-466844.csv
测试集：https://s3.cn-north-1.amazonaws.com.cn/files.datafountain.cn/uploads/images/competitions/449/test-141999.zip
测试集：https://s3.cn-north-1.amazonaws.com.cn/files.datafountain.cn/uploads/images/competitions/449/test-439524.csv
字段说明:https://s3.cn-north-1.amazonaws.com.cn/files.datafountain.cn/uploads/images/competitions/449/%E5%AD%97%E6%AE%B5%E8%AF%B4%E6%98%8E-114415.xlsx
提交样例:https://s3.cn-north-1.amazonaws.com.cn/files.datafountain.cn/uploads/images/competitions/449/submission-201941.csv

**Comment by yranky** [comment]
![image](https://user-images.githubusercontent.com/53134806/204083230-693e4d2b-e0f8-4742-a19b-4349e83c41b3.png)
训练集：https://s3.cn-north-1.amazonaws.com.cn/files.datafountain.cn/uploads/images/competitions/449/train-466844.csv
测试集：https://s3.cn-north-1.amazonaws.com.cn/files.datafountain.cn/uploads/images/competitions/449/test-141999.zip
测试集：https://s3.cn-north-1.amazonaws.com.cn/files.datafountain.cn/uploads/images/competitions/449/test-439524.csv
字段说明:https://s3.cn-north-1.amazonaws.com.cn/files.datafountain.cn/uploads/images/competitions/449/%E5%AD%97%E6%AE%B5%E8%AF%B4%E6%98%8E-114415.xlsx
提交样例:https://s3.cn-north-1.amazonaws.com.cn/files.datafountain.cn/uploads/images/competitions/449/submission-201941.csv

**Comment by woxiangzhuandaqian** [comment]
谢谢

**Comment by yranky** [comment]
不客气
